#!/bin/bash
# Display help for all database scripts

echo "🗄️  Bomizzel Database Scripts"
echo "=============================="
echo ""
echo "📖 Quick Reference: QUICK_DB_REFERENCE.md"
echo "📚 Full Guide: DATABASE_GUIDE.md"
echo ""
echo "Available Scripts:"
echo ""
echo "1️⃣  ./scripts/db-common-queries.sh [command]"
echo "   Pre-built queries for common tasks"
echo "   Commands: tables, users, companies, subscriptions, provisioned, admin, inactive, count, schema"
echo ""
echo "2️⃣  ./scripts/db-query.sh \"SQL QUERY\""
echo "   Run a custom SQL query"
echo "   Example: ./scripts/db-query.sh \"SELECT * FROM users LIMIT 5;\""
echo ""
echo "3️⃣  ./scripts/db-shell.sh"
echo "   Open interactive PostgreSQL shell"
echo ""
echo "4️⃣  ./scripts/db-fix.sh [command] [args]"
echo "   Fix common database issues"
echo "   Commands: enable-user, disable-user, make-admin, verify-email,"
echo "            enable-company, disable-company, activate-subscription,"
echo "            suspend-subscription, enable-all-company-users, disable-all-company-users"
echo ""
echo "5️⃣  ./scripts/db-backup.sh [name]"
echo "   Create a database backup"
echo "   Example: ./scripts/db-backup.sh my-backup"
echo ""
echo "6️⃣  ./scripts/db-restore.sh [backup-file]"
echo "   Restore database from backup"
echo "   Example: ./scripts/db-restore.sh backups/backup.sql.gz"
echo ""
echo "Quick Examples:"
echo "---------------"
echo "# View all users"
echo "./scripts/db-common-queries.sh users"
echo ""
echo "# Enable a user"
echo "./scripts/db-fix.sh enable-user user@example.com"
echo ""
echo "# Create backup"
echo "./scripts/db-backup.sh"
echo ""
echo "# Custom query"
echo "./scripts/db-query.sh \"SELECT COUNT(*) FROM tickets;\""
echo ""
echo "For detailed help on any script, run it without arguments."
